name: Build and Deploy API

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: PRD
    env:
      ASPNETCORE_ENVIRONMENT: ${{ secrets.ASPNETCORE_ENVIRONMENT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Test and lint
        uses: ./.github/workflows/test-and-lint.yml

      - name: Calculate version based on pushes this month
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          YEAR=$(date +'%y')
          MONTH=$(date +'%m')

          # Get first day of the current month in ISO 8601 format
          FIRST_DAY_OF_MONTH=$(date -u +'%Y-%m-01T00:00:00Z')

          # Count commits on main since FIRST_DAY_OF_MONTH using GitHub API
          COMMIT_COUNT=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/commits?sha=main&since=${FIRST_DAY_OF_MONTH}" | jq length)

          VERSION="$YEAR.$MONTH.$COMMIT_COUNT"

          echo "API_VERSION=$VERSION" >> $GITHUB_ENV
          echo "API_VERSION=$VERSION"

      - name: Log in to Docker Hub
        run: echo "${{ env.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build \
            --build-arg API_VERSION=${API_VERSION} \
            -t "${{ env.DOCKERHUB_USERNAME }}/shard-api:${API_VERSION}" \
            -t "${{ env.DOCKERHUB_USERNAME }}/shard-api:latest" \
            .

      - name: Push Docker image to Docker Hub
        run: |
          docker push "${{ env.DOCKERHUB_USERNAME }}"/shard-api:${API_VERSION}
          docker push "${{ env.DOCKERHUB_USERNAME }}"/shard-api:latest
        