name: Build and Deploy API

on:
  push:
    branches: [main]

env:
  ASPNETCORE_ENVIRONMENT: Production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get current date-based version
        id: version
        run: |
          YEAR=$(date +'%y')
          MONTH=$(date +'%m')
          PATCH=$(git rev-list --count HEAD)
          VERSION="$YEAR.$MONTH.$PATCH"
          echo "API_VERSION=$VERSION" >> $GITHUB_ENV
          echo "API_VERSION=$VERSION"
      
      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build \
            --build-arg API_VERSION=${API_VERSION} \
            -t ${DOCKERHUB_USERNAME}/shard-api:${API_VERSION} .

      - name: Push Docker image to Docker Hub
        run: docker push ${DOCKERHUB_USERNAME}/shard-api:${API_VERSION}
