name: Test and Lint

on:
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run linting
        run: |
          dotnet tool install -g dotnet-format
          export PATH="$PATH:/home/runner/.dotnet/tools"
          dotnet format shard.sln --verify-no-changes

      - name: Build
        run: dotnet build --no-restore

      - name: Run all tests (unit + integration)
        run: dotnet test --no-build --verbosity normal
